/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.EventOrganizerRole;

import Business.EcoSystem;
import Business.Network.Network;
import Business.Enterprise.Enterprise;
import Business.Organization.*;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EventWorkRequest;
import Business.WorkQueue.WorkQueue;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author saikr
 */
public class CreateEventJPanel extends javax.swing.JPanel {
        private JPanel processContainerUser;
    private  CampaignManagement Organisation;
    private Enterprise enterprise;
        private UserAccount userAccount;
        private EcoSystem ecosystem;
    /**
     * Creates new form CreateEventJPanel
     */
    public CreateEventJPanel(JPanel userProcessContainer,UserAccount userAccount,Enterprise enterprise,EcoSystem ecosystem) {
       initComponents();
        this.processContainerUser = userProcessContainer;
        this.userAccount = userAccount;
        this.enterprise = enterprise;
        this.ecosystem = ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlEventName = new javax.swing.JLabel();
        jlVenue = new javax.swing.JLabel();
        jlCreateNewOrgan = new javax.swing.JLabel();
        txtEventNAme = new javax.swing.JTextField();
        txtVenuee = new javax.swing.JTextField();
        jlDate = new javax.swing.JLabel();
        jlTime = new javax.swing.JLabel();
        txtHours = new javax.swing.JTextField();
        txtMinute = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jlPurpose = new javax.swing.JLabel();
        txtPurpose = new javax.swing.JTextField();
        jlFunds = new javax.swing.JLabel();
        txtFunds = new javax.swing.JTextField();
        txtDate = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(0, 204, 204));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jlEventName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlEventName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlEventName.setText("Event Name:");

        jlVenue.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlVenue.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlVenue.setText("Venue:");

        jlCreateNewOrgan.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jlCreateNewOrgan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCreateNewOrgan.setText("CREATE NEW ORGAN DONATION EVENT");

        txtEventNAme.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtVenuee.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtVenuee.setText(" ");
        txtVenuee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVenueeActionPerformed(evt);
            }
        });

        jlDate.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlDate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlDate.setText("Date:");

        jlTime.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlTime.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlTime.setText("Time:");

        txtHours.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtHours.setText("HH");

        txtMinute.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtMinute.setText("MM");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText(":");

        btnCreate.setBackground(new java.awt.Color(204, 204, 204));
        btnCreate.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jlPurpose.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlPurpose.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlPurpose.setText("Purpose:");

        txtPurpose.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlFunds.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlFunds.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlFunds.setText("Funds Required:");

        txtFunds.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jlCreateNewOrgan, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(307, 307, 307)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jlEventName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlFunds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlPurpose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlTime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlVenue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVenuee, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19)))
                        .addGap(122, 122, 122)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(txtMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtEventNAme, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(txtPurpose, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(txtFunds)
                        .addComponent(txtDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(444, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jlCreateNewOrgan)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlEventName)
                            .addComponent(txtEventNAme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlPurpose)
                            .addComponent(txtPurpose, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFunds, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlFunds))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlDate)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jlTime)
                                .addComponent(txtMinute, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlVenue)
                            .addComponent(txtVenuee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jLabel1)))
                .addGap(27, 27, 27)
                .addComponent(btnCreate)
                .addContainerGap(379, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCreate, jlDate, jlEventName, jlFunds, jlPurpose, jlTime, jlVenue, txtEventNAme, txtFunds, txtHours, txtMinute, txtPurpose, txtVenuee});

    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        String message = txtEventNAme.getText();
        String venue = txtVenuee.getText();
        Date d = (txtDate.getDate());
        Date today = new Date(); 
        String t = txtHours.getText()+":"+txtMinute.getText();
        EventWorkRequest request = new EventWorkRequest();
        request = (EventWorkRequest) request;
        request.setMessage(message);
        request.setVenue(venue);
        request.setDate(d);
        request.setTime(t);
        request.setStatus("Request Submitted");
        if(message.equals("")){
            JOptionPane.showMessageDialog(null, "Event Name can't be empty");
            return;
        }
        if(venue.equals("")){
            JOptionPane.showMessageDialog(null, "Venue can't be empty");
            return;
        }
        
        if (!d.after(today)) {
            JOptionPane.showMessageDialog(null, "Please select a proper date");
            return;
        }
        
        
        int hrs=0;
        int min=0;
        try{
            hrs = Integer.parseInt(txtHours.getText());
            min = Integer.parseInt(txtMinute.getText());
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, "Please enter only numbers");
         return;
        }
        if(hrs<0 || hrs >=24){
             JOptionPane.showMessageDialog(null, "Hours Should be between 0-23");
             return;
        }
         if(min<0 || min >=60){
             JOptionPane.showMessageDialog(null, "Minutes Should be between 0-60");
             return;
        }
        request.setSender(userAccount);
        request.setMessage(message);
        request.setComment(txtPurpose.getText());
        request.setAmount(txtFunds.getText());
        if(userAccount.getWorkQueue()==null){
            WorkQueue wq = new WorkQueue();
                 userAccount.setWorkQueue(wq);
        }
        userAccount.getWorkQueue().getWorkRequestList().add(request);
        Organization org = null;
        for(Network network:ecosystem.getNetworkList()){
        for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
        for(Organization organization:enterprise.getOrganizationDirectory().getOrganizationList()){
         System.out.println("Sai"+organization.getOrganizationName());
         if(organization instanceof AccountsAndCompliance){
         System.out.println("Sandeep"+organization.getOrganizationName()); 
         for (UserAccount ua :organization.getUserAccountDirectory().getUserAccountList()){
                 
                if(organization instanceof AccountsAndCompliance){
       if(ua.getWorkQueue()== null){
                 WorkQueue wq = new WorkQueue();
                 ua.setWorkQueue(wq);}
                    
         ua.getWorkQueue().getWorkRequestList().add(request);
         request.setReceiver(ua);
                break;} }
                    if (organization instanceof CampaignManagement) {
                        System.out.println("Organization: "+organization);
                        org= organization;
                        break;
                    }
                }

            }
        }


        if (org != null) {


                   }}
        processContainerUser.remove(this);
        Component[] componentArray = processContainerUser.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EventOrganizerWorkAreaJPanel eowajp = (EventOrganizerWorkAreaJPanel ) component;
        eowajp.populateRequestTable();
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.previous(processContainerUser);
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        processContainerUser.remove(this);
        Component[] componentArray = processContainerUser.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EventOrganizerWorkAreaJPanel eowajp = (EventOrganizerWorkAreaJPanel ) component;
        eowajp.populateRequestTable();
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.previous(processContainerUser);
        
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtVenueeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVenueeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVenueeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlCreateNewOrgan;
    private javax.swing.JLabel jlDate;
    private javax.swing.JLabel jlEventName;
    private javax.swing.JLabel jlFunds;
    private javax.swing.JLabel jlPurpose;
    private javax.swing.JLabel jlTime;
    private javax.swing.JLabel jlVenue;
    private com.toedter.calendar.JDateChooser txtDate;
    private javax.swing.JTextField txtEventNAme;
    private javax.swing.JTextField txtFunds;
    private javax.swing.JTextField txtHours;
    private javax.swing.JTextField txtMinute;
    private javax.swing.JTextField txtPurpose;
    private javax.swing.JTextField txtVenuee;
    // End of variables declaration//GEN-END:variables
}
