/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.EventOrganizerRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.Organization.CampaignManagement;
import Business.Organization.Organization;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EventWorkRequest;
import Business.WorkQueue.WorkQueue;

import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
//import userinterface.DoctorRole.RequestLabTestJPanel;

/**
 *
 * @author saikr
 */
public class EventOrganizerWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel processContainerUser;
    private CampaignManagement Organisation;
    private Enterprise Enterprise;
    private UserAccount accountUser;
    private EnterpriseDirectory enterpriseDirectory;
    private EcoSystem ecoSystem;

    /**
     * Creates new form EventOrganizerWorkAreaJPanel
     */
    public EventOrganizerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, CampaignManagement organization, EcoSystem system) {
        initComponents();
          this.processContainerUser = userProcessContainer;
          this.accountUser=account;
          this.Organisation = organization;
          this.ecoSystem = system;
//          valueLabel.setText(enterprise.getName());
          

        //profileName.setText(userAccount.getUsername());
        //quals.setText(userAccount.getQualifications());
         // profilepic();
          populateRequestTable();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlOrganDonation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEventDetails = new javax.swing.JTable();
        btncreate = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 800));

        jlOrganDonation.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jlOrganDonation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlOrganDonation.setText("ORGAN DONATION EVENT WORK AREA");

        tableEventDetails.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tableEventDetails.setForeground(new java.awt.Color(255, 0, 51));
        tableEventDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Event Name", "Purpose", "Funds Required", "Date", "Time", "Venue", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEventDetails.setGridColor(new java.awt.Color(0, 51, 51));
        tableEventDetails.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tableEventDetails.setSelectionForeground(new java.awt.Color(255, 255, 0));
        jScrollPane1.setViewportView(tableEventDetails);

        btncreate.setBackground(new java.awt.Color(204, 204, 204));
        btncreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btncreate.setForeground(new java.awt.Color(255, 0, 51));
        btncreate.setText("Create New Event ");
        btncreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncreateActionPerformed(evt);
            }
        });

        btnRefresh.setBackground(new java.awt.Color(204, 204, 204));
        btnRefresh.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlOrganDonation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btncreate))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRefresh)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 773, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(313, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlOrganDonation)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncreate, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnRefresh, btncreate});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btncreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncreateActionPerformed
        // TODO add your handling code here:
         CardLayout layout = (CardLayout) processContainerUser.getLayout();
        processContainerUser.add("CreateEventJPanel", new CreateEventJPanel(processContainerUser, accountUser, Enterprise,ecoSystem));
        layout.next(processContainerUser);
    }//GEN-LAST:event_btncreateActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        populateRequestTable();
    }//GEN-LAST:event_btnRefreshActionPerformed
public void populateRequestTable(){
    
    
    if(accountUser.getWorkQueue()==null){}
    else{
     DefaultTableModel model = (DefaultTableModel) tableEventDetails.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : accountUser.getWorkQueue().getWorkRequestList()){
             if(request instanceof EventWorkRequest){
            Object[] row = new Object[8];
            row[0] = request;
            row[5] = ((EventWorkRequest) request).getVenue();
            row[3] = ((EventWorkRequest) request).getDate();
            row[4] =((EventWorkRequest) request).getTime();
            row[2] =((EventWorkRequest) request).getAmount();
            row[1] =((EventWorkRequest) request).getComment();
            row[6] =((EventWorkRequest) request).getStatus();
            
            model.addRow(row);}
        }
    }
        
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btncreate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlOrganDonation;
    private javax.swing.JTable tableEventDetails;
    // End of variables declaration//GEN-END:variables
}
