/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PhysicianRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Physician;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PhysicianWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author bhavana <your.name at your.org>
 */
public class TherapistWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TherapistWorkAreaJPanel
     */
    JPanel processContainerUser;
    UserAccount Account;
    Physician organization;
    Enterprise Enterprise;
    EcoSystem ecoSystem;
    Network Network;
    
    public TherapistWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, Physician organization, Enterprise enterprise, EcoSystem ecosystem, Network network) {
        initComponents();
        this.processContainerUser=userProcessContainer;
        this.Account=account;
        this.organization=organization;
        this.Enterprise=enterprise;
        this.ecoSystem=ecosystem;
        this.Network=network;
        initTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransplantPhysicians = new javax.swing.JTable();
        btnAssignMe = new javax.swing.JButton();
        jlTransplant = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        tableTransplantPhysicians.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableTransplantPhysicians.setForeground(new java.awt.Color(255, 51, 51));
        tableTransplantPhysicians.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Patient Name", "Doctor name", "Request Date", "Therapist", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTransplantPhysicians.setSelectionBackground(new java.awt.Color(255, 153, 153));
        tableTransplantPhysicians.setSelectionForeground(new java.awt.Color(255, 255, 0));
        jScrollPane1.setViewportView(tableTransplantPhysicians);

        btnAssignMe.setBackground(new java.awt.Color(204, 204, 204));
        btnAssignMe.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnAssignMe.setText("Assign me");
        btnAssignMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignMeActionPerformed(evt);
            }
        });

        jlTransplant.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jlTransplant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTransplant.setText("Transplant physicians");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
                            .addComponent(jlTransplant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(463, 463, 463)
                        .addComponent(btnAssignMe)))
                .addContainerGap(306, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jlTransplant, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAssignMe)
                .addContainerGap(432, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void initTable(){
        DefaultTableModel model = (DefaultTableModel) tableTransplantPhysicians.getModel();
        model.setRowCount(0);
        for (WorkRequest w:organization.getWorkQueue().getWorkRequestList()) {
                Object[] row = new Object[6];
                row[0] = ((PhysicianWorkRequest)w).getPatient().getId();
                row[1] = ((PhysicianWorkRequest)w).getPatient().getPatientName();
                row[2] = w.getSender();
                row[3] = w.getRequestDate();
                row[4] = w.getReceiver();
                row[5] = w.getStatus();
                model.addRow(row);   
        }                
    }
    
    
    private void btnAssignMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignMeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableTransplantPhysicians.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please select the request to assign");
            return;
        }

        WorkRequest request = null;
        for(WorkRequest w:organization.getWorkQueue().getWorkRequestList()){
            if(Integer.parseInt(""+tableTransplantPhysicians.getValueAt(tableTransplantPhysicians.getSelectedRow(), 0))==((PhysicianWorkRequest)w).getPatient().getId()){
             request=w;
             break;
            }
        }

        if(request.getStatus().equalsIgnoreCase("Assigned")){
            JOptionPane.showMessageDialog(null,"This patient is assigned");
        }
        request.setStatus("Assigned");
        request.setReceiver(Account);
        initTable();
        
    }//GEN-LAST:event_btnAssignMeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignMe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlTransplant;
    private javax.swing.JTable tableTransplantPhysicians;
    // End of variables declaration//GEN-END:variables
}
