/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.LabAssistantRole;

import Business.WorkQueue.DiagnosticsWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author vidyavathipuli
 */
public class ProcessDiagnostics extends javax.swing.JPanel {

    JPanel processContainerUser;
    DiagnosticsWorkRequest Request;
    private String Others;

  
    public ProcessDiagnostics(JPanel userProcessContainer, DiagnosticsWorkRequest request) {
        initComponents();
        this.processContainerUser = userProcessContainer;
        this.Request = request;
        initlables();

    }

    public void initlables() {
   
        jlBloodType.setVisible(false);
        comboBloodType.setVisible(false);
        jlSurvival.setVisible(false);
        comboSurvival.setVisible(false);
        jlAntibody.setVisible(false);
        comboAntibody.setVisible(false);
        jlWBC.setVisible(false);
        jlLiver.setVisible(false);
        jlKidney.setVisible(false);
        comboWbc.setVisible(false);
        comboLiver.setVisible(false);
        comboKidney.setVisible(false);
        jlRandom.setVisible(false);
        comboRandom.setVisible(false);
        txt_random2.setVisible(false);
        cb_random2.setVisible(false);
        txt_random2.setVisible(false);
        cb_random2.setVisible(false);
        txt_random3.setVisible(false);
        cb_random3.setVisible(false);
        
        List<JLabel> labels = Arrays.asList(jlRandom, txt_random2, txt_random3);
        List<JComboBox> cboxes = Arrays.asList(comboRandom, cb_random2, cb_random3);
        int counter=0;
        
        System.out.println("Test Array in lab process"+Request.getTests());
        for (String s : Request.getTests()) {          
            
            if (s.equalsIgnoreCase("blood typing")) {
                jlBloodType.setVisible(true);
                comboBloodType.setVisible(true);    
            }
            if (s.equalsIgnoreCase("survival capability")) {
                jlAntibody.setVisible(true);
                comboAntibody.setVisible(true);
            }
            if (s.equalsIgnoreCase("reactive antibodies")) {
                jlSurvival.setVisible(true);
                comboSurvival.setVisible(true);
            }
            if (s.equalsIgnoreCase("wbc count")) {
                jlWBC.setVisible(true);
                comboWbc.setVisible(true);
            }
            if (s.equalsIgnoreCase("liver culture")) {
                jlLiver.setVisible(true);
                comboLiver.setVisible(true);
            }
            if (s.equalsIgnoreCase("kidney culture")) {
                jlKidney.setVisible(true);
                comboKidney.setVisible(true);
            }           
            
            if (!(s.equalsIgnoreCase("kidney culture")||s.equalsIgnoreCase("liver culture")||s.equalsIgnoreCase("wbc count")||s.equalsIgnoreCase("blood typing") || s.equalsIgnoreCase("survival capability") || s.equalsIgnoreCase("reactive antibodies"))) {
                labels.get(counter).setVisible(true);
                labels.get(counter).setText(s);
                cboxes.get(counter).setVisible(true);
                //others=s;
                counter++;

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGenerate = new javax.swing.JButton();
        jlResult = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        jlBloodType = new javax.swing.JLabel();
        jlSurvival = new javax.swing.JLabel();
        jlAntibody = new javax.swing.JLabel();
        comboBloodType = new javax.swing.JComboBox();
        comboSurvival = new javax.swing.JComboBox();
        comboAntibody = new javax.swing.JComboBox();
        jlRandom = new javax.swing.JLabel();
        comboRandom = new javax.swing.JComboBox();
        jlLabTest = new javax.swing.JLabel();
        jlWBC = new javax.swing.JLabel();
        jlLiver = new javax.swing.JLabel();
        jlKidney = new javax.swing.JLabel();
        comboWbc = new javax.swing.JComboBox<>();
        comboLiver = new javax.swing.JComboBox<>();
        comboKidney = new javax.swing.JComboBox<>();
        cb_random2 = new javax.swing.JComboBox();
        txt_random2 = new javax.swing.JLabel();
        cb_random3 = new javax.swing.JComboBox();
        txt_random3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        btnGenerate.setBackground(new java.awt.Color(204, 204, 204));
        btnGenerate.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnGenerate.setText("Generate Result");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        jlResult.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlResult.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlResult.setText("Result:");

        txtResult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btn_back.setBackground(new java.awt.Color(204, 204, 204));
        btn_back.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_back.setText("Back");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        jlBloodType.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlBloodType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlBloodType.setText("Blood Typing");

        jlSurvival.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlSurvival.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlSurvival.setText("Survival Capability");

        jlAntibody.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlAntibody.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlAntibody.setText("Reactive Antibodies");

        comboBloodType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboBloodType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Normal ", "Abnormal", " " }));

        comboSurvival.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboSurvival.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Normal ", "Abnormal", " " }));
        comboSurvival.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboSurvivalActionPerformed(evt);
            }
        });

        comboAntibody.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboAntibody.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "10%-20%", "20%-40%", "40%-60%", "60%-80%", ">80%", " " }));
        comboAntibody.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAntibodyActionPerformed(evt);
            }
        });

        jlRandom.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlRandom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlRandom.setText("Random:");

        comboRandom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboRandom.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Normal ", "Abnormal", " " }));
        comboRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboRandomActionPerformed(evt);
            }
        });

        jlLabTest.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jlLabTest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlLabTest.setText("LAB TESTS");

        jlWBC.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlWBC.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlWBC.setText("WBC Count");

        jlLiver.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlLiver.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlLiver.setText("Liver Culture");

        jlKidney.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlKidney.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlKidney.setText("Kidney Culture :");

        comboWbc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboWbc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Normal ", "Abnormal" }));

        comboLiver.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboLiver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Normal ", "Abnormal" }));

        comboKidney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboKidney.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Normal ", "Abnormal" }));

        cb_random2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_random2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Normal ", "Abnormal", " " }));
        cb_random2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_random2ActionPerformed(evt);
            }
        });

        txt_random2.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_random2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_random2.setText("Random:");

        cb_random3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cb_random3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "Normal ", "Abnormal", " " }));
        cb_random3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_random3ActionPerformed(evt);
            }
        });

        txt_random3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txt_random3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt_random3.setText("Random:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlLabTest, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlSurvival)
                            .addComponent(jlAntibody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlBloodType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlWBC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlLiver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlKidney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlRandom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_random2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_random3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(comboLiver, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboKidney, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboBloodType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboSurvival, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboAntibody, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboWbc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboRandom, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_random2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_random3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtResult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGenerate)
                .addGap(405, 405, 405))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlLabTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlBloodType)
                    .addComponent(comboBloodType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlSurvival)
                    .addComponent(comboSurvival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAntibody)
                    .addComponent(comboAntibody, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlWBC)
                    .addComponent(comboWbc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlLiver)
                    .addComponent(comboLiver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlKidney)
                    .addComponent(comboKidney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRandom)
                    .addComponent(comboRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_random2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_random2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_random3)
                    .addComponent(cb_random3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlResult))
                .addGap(34, 34, 34)
                .addComponent(btnGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        processContainerUser.remove(this);
        Component[] componentArray = processContainerUser.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DiagnosticsWorkArea dwjp = (DiagnosticsWorkArea) component;
        dwjp.initWorktable();
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.previous(processContainerUser);
    }//GEN-LAST:event_btn_backActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        Request.setTestResult(txtResult.getText());
        String test1 = comboBloodType.getSelectedItem().toString();    
        String test2 = comboSurvival.getSelectedItem().toString();
        String test3 = comboAntibody.getSelectedItem().toString();
        String test4 = comboWbc.getSelectedItem().toString();
        String test5 = comboLiver.getSelectedItem().toString();
        String test6 = comboKidney.getSelectedItem().toString();
        String test7 = comboRandom.getSelectedItem().toString();
        String test8 = cb_random2.getSelectedItem().toString();
        String test9 = cb_random3.getSelectedItem().toString();
        
        ArrayList<String> sample= new ArrayList<>();
     
        if(!(test1=="-"||test1.isEmpty()||test1.isEmpty())){
            sample.add(test1);
        }
        if(!(test2=="-"||test2.isEmpty()||test2.isEmpty())){
            sample.add(test2);
        }
        if(!(test3=="-"||test3.isEmpty()||test3.isEmpty())){
            sample.add(test3);
        }
        if(!(test4=="-"||test4.isEmpty()||test4.isEmpty())){
            sample.add(test4);
        }
        if(!(test5=="-"||test5.isEmpty()||test5.isEmpty())){
            sample.add(test5);
        }
        if(!(test6=="-"||test6.isEmpty()||test6.isEmpty())){
            sample.add(test6);
        }
        if(!(test7=="-"||test7.isEmpty()||test7.isEmpty())){
            sample.add(test7);
        }
        if(!(test8=="-"||test8.isEmpty()||test8.isEmpty())){
            sample.add(test8);
        }
        if(!(test9=="-"||test9.isEmpty()||test9.isEmpty())){
            sample.add(test9);
        }
        
        boolean check;
        check=sample.size()>0;
        if(!check){
            JOptionPane.showMessageDialog(null, "Please perform the tests for proper evaluation");
            return;
        }
        Request.setTestData(sample);
        Request.setStatus("Completed");
        JOptionPane.showMessageDialog(null,"Report has been sent");
        System.out.println(Request.getTestData()+"This is test data");
        
        processContainerUser.remove(this);
        Component[] componentArray = processContainerUser.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DiagnosticsWorkArea dwjp = (DiagnosticsWorkArea) component;
        dwjp.initWorktable();
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.previous(processContainerUser);
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void comboAntibodyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAntibodyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAntibodyActionPerformed

    private void comboRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboRandomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboRandomActionPerformed

    private void comboSurvivalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSurvivalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSurvivalActionPerformed

    private void cb_random2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_random2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_random2ActionPerformed

    private void cb_random3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_random3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_random3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btn_back;
    private javax.swing.JComboBox cb_random2;
    private javax.swing.JComboBox cb_random3;
    private javax.swing.JComboBox comboAntibody;
    private javax.swing.JComboBox comboBloodType;
    private javax.swing.JComboBox<String> comboKidney;
    private javax.swing.JComboBox<String> comboLiver;
    private javax.swing.JComboBox comboRandom;
    private javax.swing.JComboBox comboSurvival;
    private javax.swing.JComboBox<String> comboWbc;
    private javax.swing.JLabel jlAntibody;
    private javax.swing.JLabel jlBloodType;
    private javax.swing.JLabel jlKidney;
    private javax.swing.JLabel jlLabTest;
    private javax.swing.JLabel jlLiver;
    private javax.swing.JLabel jlRandom;
    private javax.swing.JLabel jlResult;
    private javax.swing.JLabel jlSurvival;
    private javax.swing.JLabel jlWBC;
    private javax.swing.JTextField txtResult;
    private javax.swing.JLabel txt_random2;
    private javax.swing.JLabel txt_random3;
    // End of variables declaration//GEN-END:variables
}
