

package ui.AdministrativeRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  bhavana
 */
public class HospitalAdminJPanel extends javax.swing.JPanel {
    
    JPanel processContainerUser;
    Enterprise Enterprise;
    EcoSystem ecosystem;
    Network Network;
    /** Creates new form AdminWorkAreaJPanel */
    public HospitalAdminJPanel(JPanel userProcessContainer, Enterprise enterprise,EcoSystem ecoSystem,Network network) {
        initComponents();
        this.processContainerUser = userProcessContainer;
        this.Enterprise = enterprise;
        this.ecosystem=ecoSystem;
        this.Network=network;
        System.out.println(enterprise.getOrganizationName().concat("hospital"));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlHospitalAdminDashBoard = new javax.swing.JLabel();
        btnManageUserAccount = new javax.swing.JButton();
        btnManageOrganisation = new javax.swing.JButton();
        btnManageEmployees = new javax.swing.JButton();
        btnManagePatients = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jlHospitalAdminDashBoard.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jlHospitalAdminDashBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlHospitalAdminDashBoard.setText("HOSPITAL ADMIN DASHBOARD");

        btnManageUserAccount.setBackground(new java.awt.Color(204, 204, 204));
        btnManageUserAccount.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnManageUserAccount.setText("Manage User Accounts");
        btnManageUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccountActionPerformed(evt);
            }
        });

        btnManageOrganisation.setBackground(new java.awt.Color(204, 204, 204));
        btnManageOrganisation.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnManageOrganisation.setText("Manage Organization");
        btnManageOrganisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganisationActionPerformed(evt);
            }
        });

        btnManageEmployees.setBackground(new java.awt.Color(204, 204, 204));
        btnManageEmployees.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnManageEmployees.setText("Manage Employees");
        btnManageEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeesActionPerformed(evt);
            }
        });

        btnManagePatients.setBackground(new java.awt.Color(204, 204, 204));
        btnManagePatients.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnManagePatients.setText("Manage Patients");
        btnManagePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatientsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(383, 383, 383)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageOrganisation, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManagePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnManageEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jlHospitalAdminDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 743, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jlHospitalAdminDashBoard)
                .addGap(70, 70, 70)
                .addComponent(btnManageOrganisation, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManagePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccountActionPerformed
        UserManagement em = new UserManagement(processContainerUser, Enterprise);
        processContainerUser.add("ManageUserAccountJPanel", em);
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_btnManageUserAccountActionPerformed

    private void btnManageOrganisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganisationActionPerformed
        OrganizationManagementJPanel omj = new OrganizationManagementJPanel(processContainerUser, Enterprise.getOrganizationDirectory(),Enterprise);
        processContainerUser.add("manageOrganizationJPanel", omj);
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_btnManageOrganisationActionPerformed

    private void btnManageEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeesActionPerformed
        // TODO add your handling code here:
        EmployeeManagement em = new EmployeeManagement(processContainerUser, Enterprise.getOrganizationDirectory(),Enterprise,ecosystem);
        processContainerUser.add("manageOrganizationJPanel", em);
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_btnManageEmployeesActionPerformed

    private void btnManagePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatientsActionPerformed
        // TODO add your handling code here:
        PatientManagement pm = new PatientManagement(processContainerUser, Enterprise.getOrganizationDirectory(),Enterprise,ecosystem);
        processContainerUser.add("manageOrganizationJPanel", pm);
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_btnManagePatientsActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageEmployees;
    private javax.swing.JButton btnManageOrganisation;
    private javax.swing.JButton btnManagePatients;
    private javax.swing.JButton btnManageUserAccount;
    private javax.swing.JLabel jlHospitalAdminDashBoard;
    // End of variables declaration//GEN-END:variables
    
}
