/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.HealthOfficer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.EnterpriseDirectory;
import Business.Network.Network;
import Business.Organization.CampaignManagement;
import Business.Organization.AccountsAndCompliance;
import Business.Person.Donor;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.EventWorkRequest;
import Business.WorkQueue.WorkRequest;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
* @author saikr
 */
public class HealthOfficerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNGOJPanel
     */
    private JPanel userProcessContainer;
    private CampaignManagement campAwareness;
    private AccountsAndCompliance Organisation;
    private Enterprise Enterprise;
    private UserAccount userAccount;
    private EnterpriseDirectory directoryEnterprise;
    private EcoSystem ecoSystem;
    public HealthOfficerJPanel(JPanel userProcessContainer, UserAccount account, AccountsAndCompliance organization, Enterprise enterprise, EcoSystem business, Network network) {
       
        initComponents();
          this.userProcessContainer = userProcessContainer;
          this.userAccount=account;
          this.Organisation = organization;
          this.ecoSystem = business;

          populateRequestTable();
          populate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlOrganDonation = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEvent = new javax.swing.JTable();
        btnAccepetRequest = new javax.swing.JButton();
        btnDeclineRequest = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDonarList = new javax.swing.JTable();
        jlDonarList = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 204));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jlOrganDonation.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jlOrganDonation.setText("Organ Donation Event Fund Requests :  ");

        tableEvent.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableEvent.setForeground(new java.awt.Color(255, 0, 51));
        tableEvent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Event Name", "Purpose", "Funds Required", "Date", "Time", "Venue", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableEvent.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tableEvent.setSelectionForeground(new java.awt.Color(255, 255, 51));
        jScrollPane1.setViewportView(tableEvent);

        btnAccepetRequest.setBackground(new java.awt.Color(204, 204, 204));
        btnAccepetRequest.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnAccepetRequest.setText("ACCEPT REQUEST");
        btnAccepetRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccepetRequestActionPerformed(evt);
            }
        });

        btnDeclineRequest.setBackground(new java.awt.Color(204, 204, 204));
        btnDeclineRequest.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btnDeclineRequest.setText("DECLINE REQUEST");
        btnDeclineRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineRequestActionPerformed(evt);
            }
        });

        tableDonarList.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableDonarList.setForeground(new java.awt.Color(255, 0, 0));
        tableDonarList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Donor Name", "Contact"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDonarList.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tableDonarList.setSelectionForeground(new java.awt.Color(255, 255, 51));
        jScrollPane2.setViewportView(tableDonarList);

        jlDonarList.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jlDonarList.setText("Donor list :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAccepetRequest)
                        .addGap(34, 34, 34)
                        .addComponent(btnDeclineRequest))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlOrganDonation)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 845, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlDonarList, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAccepetRequest, btnDeclineRequest});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jlOrganDonation)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccepetRequest)
                    .addComponent(btnDeclineRequest))
                .addGap(37, 37, 37)
                .addComponent(jlDonarList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(456, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAccepetRequest, btnDeclineRequest});

    }// </editor-fold>//GEN-END:initComponents

    private void btnDeclineRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineRequestActionPerformed
    
        int selectedRow = tableEvent.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        System.out.println(tableEvent.getValueAt(selectedRow, 0));
        EventWorkRequest ewr = (EventWorkRequest)tableEvent.getValueAt(selectedRow,0);
        ewr.setStatus("Declined");
        populateRequestTable();
    }//GEN-LAST:event_btnDeclineRequestActionPerformed

    private void btnAccepetRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccepetRequestActionPerformed
        // TODO add your handling code here:
         
        
        int selectedRow = tableEvent.getSelectedRow();
        if(selectedRow < 0) {
            JOptionPane.showMessageDialog(null,"Please Select a row from table first", "Warining", JOptionPane.WARNING_MESSAGE);
            return;
        }
        System.out.println(tableEvent.getValueAt(selectedRow, 0));
        EventWorkRequest ewr = (EventWorkRequest)tableEvent.getValueAt(selectedRow,0);
        ewr.setStatus("Approved");
        populateRequestTable();
        
    }//GEN-LAST:event_btnAccepetRequestActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccepetRequest;
    private javax.swing.JButton btnDeclineRequest;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel jlDonarList;
    private javax.swing.JLabel jlOrganDonation;
    private javax.swing.JTable tableDonarList;
    private javax.swing.JTable tableEvent;
    // End of variables declaration//GEN-END:variables

    private void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) tableEvent.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            
            
            if(request instanceof EventWorkRequest){
            Object[] row = new Object[7];
            row[0] = request;
            row[5] = ((EventWorkRequest) request).getVenue();
            row[3] = ((EventWorkRequest) request).getDate();
            row[4] =((EventWorkRequest) request).getTime();
            row[2] = ((EventWorkRequest) request).getAmount();
            row[1] = ((EventWorkRequest) request).getComment();
            row[6] = ((EventWorkRequest) request).getStatus();
            
            model.addRow(row);}
        }
    }
    private void populate() {
        DefaultTableModel model = (DefaultTableModel) tableDonarList.getModel();
        
        model.setRowCount(0);
        for (Donor d : ecoSystem.getDonorDirectory()){
            Object[] row = new Object[3];
            row[0] = d.getDonorName();
            row[1] = d.getContactNum();
            
            model.addRow(row);
        }
    }
}
