

package ui.AdministrativeRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  shiva
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel containerProcessUser;
    Enterprise enterprisee;
    EcoSystem ecoSystem;
    Network Network;
    /** Creates new form AdminWorkAreaJPanel
     * @param userProcessContainer
     * @param enterprise
     * @param ecoSystem
     * @param network */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,EcoSystem ecoSystem,Network network) {
        initComponents();
        this.containerProcessUser = userProcessContainer;
        this.enterprisee = enterprise;
        this.ecoSystem=ecoSystem;
        this.Network=network;
        System.out.println(enterprise.getOrganizationName().concat("hospital"));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlAdminDashBoard = new javax.swing.JLabel();
        btnUserAccountt = new javax.swing.JButton();
        btnManageOrganisation = new javax.swing.JButton();
        btnManageEmployeess = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jlAdminDashBoard.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jlAdminDashBoard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlAdminDashBoard.setText("ADMIN DASHBOARD");

        btnUserAccountt.setBackground(new java.awt.Color(204, 204, 204));
        btnUserAccountt.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnUserAccountt.setText("   Manage User Accounts");
        btnUserAccountt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccounttActionPerformed(evt);
            }
        });

        btnManageOrganisation.setBackground(new java.awt.Color(204, 204, 204));
        btnManageOrganisation.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnManageOrganisation.setText("  Manage Organization");
        btnManageOrganisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganisationActionPerformed(evt);
            }
        });

        btnManageEmployeess.setBackground(new java.awt.Color(204, 204, 204));
        btnManageEmployeess.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnManageEmployeess.setText("Manage Employees");
        btnManageEmployeess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeessActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jlAdminDashBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 983, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnManageOrganisation, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                            .addComponent(btnManageEmployeess, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                            .addComponent(btnUserAccountt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(403, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlAdminDashBoard)
                .addGap(52, 52, 52)
                .addComponent(btnManageOrganisation, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageEmployeess, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUserAccountt, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(479, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUserAccounttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccounttActionPerformed
        UserManagement em = new UserManagement(containerProcessUser, enterprisee);
        containerProcessUser.add("ManageUserAccountJPanel", em);
        CardLayout layout = (CardLayout) containerProcessUser.getLayout();
        layout.next(containerProcessUser);
    }//GEN-LAST:event_btnUserAccounttActionPerformed

    private void btnManageOrganisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganisationActionPerformed
        OrganizationManagementJPanel omj = new OrganizationManagementJPanel(containerProcessUser, enterprisee.getOrganizationDirectory(),enterprisee);
        containerProcessUser.add("manageOrganizationJPanel", omj);
        CardLayout layout = (CardLayout) containerProcessUser.getLayout();
        layout.next(containerProcessUser);
    }//GEN-LAST:event_btnManageOrganisationActionPerformed

    private void btnManageEmployeessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeessActionPerformed
        // TODO add your handling code here:
        EmployeeManagement em = new EmployeeManagement(containerProcessUser, enterprisee.getOrganizationDirectory(),enterprisee,ecoSystem);
        containerProcessUser.add("manageOrganizationJPanel", em);
        CardLayout layout = (CardLayout) containerProcessUser.getLayout();
        layout.next(containerProcessUser);
    }//GEN-LAST:event_btnManageEmployeessActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageEmployeess;
    private javax.swing.JButton btnManageOrganisation;
    private javax.swing.JButton btnUserAccountt;
    private javax.swing.JLabel jlAdminDashBoard;
    // End of variables declaration//GEN-END:variables
    
}
