

package ui.AdministrativeRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author  shiva
 */
public class OrganBankJPanel extends javax.swing.JPanel {
    
    JPanel processContainerUser;
    Enterprise Enterprise;
    EcoSystem ecosystem;
    Network Network;
    /** Creates new form AdminWorkAreaJPanel */
    public OrganBankJPanel(JPanel userProcessContainer, Enterprise enterprise,EcoSystem ecoSystem,Network network) {
        initComponents();
        this.processContainerUser = userProcessContainer;
        this.Enterprise = enterprise;
        this.ecosystem=ecoSystem;
        this.Network=network;
        System.out.println(enterprise.getOrganizationName().concat("hospital"));
      
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlOrganBankAdminDashboard = new javax.swing.JLabel();
        btnManageUserAccount = new javax.swing.JButton();
        btnManageOrganisation = new javax.swing.JButton();
        btnManageEmployees = new javax.swing.JButton();
        btnViewRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jlOrganBankAdminDashboard.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jlOrganBankAdminDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlOrganBankAdminDashboard.setText("ORGAN BANK ADMIN DASHBOARD");

        btnManageUserAccount.setBackground(new java.awt.Color(204, 204, 204));
        btnManageUserAccount.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnManageUserAccount.setText("Manage User Accounts");
        btnManageUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAccountActionPerformed(evt);
            }
        });

        btnManageOrganisation.setBackground(new java.awt.Color(204, 204, 204));
        btnManageOrganisation.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnManageOrganisation.setText("Manage Organization");
        btnManageOrganisation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrganisationActionPerformed(evt);
            }
        });

        btnManageEmployees.setBackground(new java.awt.Color(204, 204, 204));
        btnManageEmployees.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnManageEmployees.setText("Manage Employees");
        btnManageEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEmployeesActionPerformed(evt);
            }
        });

        btnViewRequest.setBackground(new java.awt.Color(204, 204, 204));
        btnViewRequest.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnViewRequest.setText("View Requests");
        btnViewRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageUserAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageOrganisation, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jlOrganBankAdminDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnManageEmployees, btnManageOrganisation, btnManageUserAccount, btnViewRequest});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jlOrganBankAdminDashboard)
                .addGap(67, 67, 67)
                .addComponent(btnManageOrganisation, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnViewRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(412, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAccountActionPerformed
        UserManagement em = new UserManagement(processContainerUser, Enterprise);
        processContainerUser.add("ManageUserAccountJPanel", em);
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_btnManageUserAccountActionPerformed

    private void btnManageOrganisationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrganisationActionPerformed
        OrganizationManagementJPanel omj = new OrganizationManagementJPanel(processContainerUser, Enterprise.getOrganizationDirectory(),Enterprise);
        processContainerUser.add("manageOrganizationJPanel", omj);
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_btnManageOrganisationActionPerformed

    private void btnManageEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEmployeesActionPerformed
        // TODO add your handling code here:
        EmployeeManagement em = new EmployeeManagement(processContainerUser, Enterprise.getOrganizationDirectory(),Enterprise,ecosystem);
        processContainerUser.add("manageOrganizationJPanel", em);
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_btnManageEmployeesActionPerformed

    private void btnViewRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRequestActionPerformed
        // TODO add your handling code here:
        OrganManagement pm = new OrganManagement(processContainerUser, Enterprise.getOrganizationDirectory(),Enterprise,ecosystem,Network);
        processContainerUser.add("manageOrgan", pm);
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_btnViewRequestActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageEmployees;
    private javax.swing.JButton btnManageOrganisation;
    private javax.swing.JButton btnManageUserAccount;
    private javax.swing.JButton btnViewRequest;
    private javax.swing.JLabel jlOrganBankAdminDashboard;
    // End of variables declaration//GEN-END:variables
    
}
