/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.AdministrativeRole;

import Business.Enterprise.Enterprise;
import Business.Enterprise.Hospital;
import Business.Enterprise.OrganBank;
import Business.Enterprise.PublicHealth;
import Business.Enterprise.Treatment;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vidyavathipuli
 */
public class OrganizationManagementJPanel extends javax.swing.JPanel {

    private OrganizationDirectory directoryOrganiser;
    private JPanel processContainerUser;
    private Enterprise Enterprise;
    /**
     * Creates new form ManageOrganizationJPanel
     */
    public OrganizationManagementJPanel(JPanel userProcessContainer,OrganizationDirectory directory,Enterprise enterprise) {
        initComponents();
        this.processContainerUser = userProcessContainer;
        this.directoryOrganiser = directory;
        this.Enterprise= enterprise;
        
        initTable();
        initComboBox();
    }
    
    
    
    private void initComboBox(){
        comboOrganisationType.removeAllItems();
        comboOrganisationType.addItem("--Choose--");
        for (Type type : Organization.Type.values()){
            
             if(Enterprise instanceof Hospital){
                 if(type.toString().equals("Medical") || type.toString().equals("Diagnostics")){
                 comboOrganisationType.addItem(type);}
             }
             if(Enterprise instanceof OrganBank){
                 if(type.toString().equals("Services")){
                 comboOrganisationType.addItem(type);}
                 
             }
             if(Enterprise instanceof PublicHealth){
                 if(type.toString().equals("AccountsAndFinance")|| type.toString().equals("CampaignManagement")){
                 comboOrganisationType.addItem(type);}
                 
             }
             if(Enterprise instanceof Treatment){
                 if(type.toString().equals("Physician")){
                 comboOrganisationType.addItem(type);}
                 
             }
                
            
        }
    }

    private void initTable(){
        DefaultTableModel model = (DefaultTableModel) tableCurruntOrganisation.getModel();
        model.setRowCount(0);
        for (Organization organization : directoryOrganiser.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationName();
            row[1]= organization.getType().getValue();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableCurruntOrganisation = new javax.swing.JTable();
        buttonAdd = new javax.swing.JButton();
        comboOrganisationType = new javax.swing.JComboBox();
        jlOrganisationType = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        jlCreateOrganisation = new javax.swing.JLabel();
        txtCurrentOrganizations = new javax.swing.JLabel();
        jlOrganisationName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        tableCurruntOrganisation.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tableCurruntOrganisation.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        tableCurruntOrganisation.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Organisation Name", "Organisation Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableCurruntOrganisation);
        if (tableCurruntOrganisation.getColumnModel().getColumnCount() > 0) {
            tableCurruntOrganisation.getColumnModel().getColumn(0).setResizable(false);
            tableCurruntOrganisation.getColumnModel().getColumn(1).setResizable(false);
        }

        buttonAdd.setBackground(new java.awt.Color(204, 204, 204));
        buttonAdd.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        buttonAdd.setText("Add");
        buttonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddActionPerformed(evt);
            }
        });

        comboOrganisationType.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        comboOrganisationType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jlOrganisationType.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jlOrganisationType.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlOrganisationType.setText("Organization Type :");

        buttonBack.setBackground(new java.awt.Color(204, 204, 204));
        buttonBack.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        jlCreateOrganisation.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jlCreateOrganisation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlCreateOrganisation.setText("CREATE ORGANIZATION");

        txtCurrentOrganizations.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        txtCurrentOrganizations.setText("Organizations List");

        jlOrganisationName.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jlOrganisationName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jlOrganisationName.setText("Organization Name :");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlCreateOrganisation, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(395, 395, 395))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jlOrganisationType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlOrganisationName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboOrganisationType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCurrentOrganizations)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCreateOrganisation)
                    .addComponent(buttonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboOrganisationType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOrganisationType))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlOrganisationName))
                .addGap(26, 26, 26)
                .addComponent(buttonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(txtCurrentOrganizations)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(300, 300, 300))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddActionPerformed

        boolean check;
        check=comboOrganisationType.getSelectedIndex()>0;
        if(!check){
            JOptionPane.showMessageDialog(null, "Select an Organisation");
        }
        
        Type type = (Type) comboOrganisationType.getSelectedItem();
        directoryOrganiser.createOrganization(type,txtName.getText());
        txtName.setText("");
        initTable();
    }//GEN-LAST:event_buttonAddActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed

        processContainerUser.remove(this);
        CardLayout layout = (CardLayout) processContainerUser.getLayout();
        layout.previous(processContainerUser);
    }//GEN-LAST:event_buttonBackActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdd;
    private javax.swing.JButton buttonBack;
    private javax.swing.JComboBox comboOrganisationType;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlCreateOrganisation;
    private javax.swing.JLabel jlOrganisationName;
    private javax.swing.JLabel jlOrganisationType;
    private javax.swing.JTable tableCurruntOrganisation;
    private javax.swing.JLabel txtCurrentOrganizations;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
