/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Treatment;
import Business.Network.Network;
import Business.Organization.Medical;
import Business.Organization.Organization;
import Business.Person.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.PhysicianWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author bhavana
 */
public class RequestTherapyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestTherapyJPanel
     */
    JPanel processContainerUser;
    UserAccount accountUser;
    String id;
    Medical org;
    EcoSystem ecosystem;
    Enterprise Enterprise;
    Network Network;
    Patient Patient;
    public RequestTherapyJPanel(JPanel userProcessContainer, Medical organization, UserAccount userAccount, Patient p, EcoSystem ecosystem, Enterprise enterprise, Network network) {
        initComponents();
        this.processContainerUser=userProcessContainer;
        this.accountUser=userAccount;
        this.id=""+p.getId();
        this.ecosystem=ecosystem;
        this.Patient=p;
        this.org=organization;
        this.Network=network;
        this.Enterprise=enterprise;
        txtPatientID.setText(id);
        txtPatientName.setText(this.Patient.getPatientName());
        display();
    }
    
    public void display(){
        comboNetwork.addItem("--Select--");
        for(Network n: ecosystem.getNetworkList()){
            comboNetwork.addItem(n.getNetworkName());
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlPatientId = new javax.swing.JLabel();
        jlPatientName = new javax.swing.JLabel();
        txtPatientID = new javax.swing.JTextField();
        txtPatientName = new javax.swing.JTextField();
        jlNetwork = new javax.swing.JLabel();
        comboNetwork = new javax.swing.JComboBox<>();
        jlTherapyCenter = new javax.swing.JLabel();
        jlCategory = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        comboTherpay = new javax.swing.JComboBox<>();
        comboCategory = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jlRequestTherapy = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jlPatientId.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlPatientId.setText("Patient ID ");

        jlPatientName.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlPatientName.setText("Patient Name ");

        txtPatientID.setEditable(false);
        txtPatientID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtPatientName.setEditable(false);
        txtPatientName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jlNetwork.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlNetwork.setText("Network ");

        comboNetwork.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        comboNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNetworkActionPerformed(evt);
            }
        });

        jlTherapyCenter.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlTherapyCenter.setText("Therapy Centers ");

        jlCategory.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlCategory.setText("Therapy Category ");

        btnSubmit.setBackground(new java.awt.Color(204, 204, 204));
        btnSubmit.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        comboTherpay.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        comboTherpay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));
        comboTherpay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTherpayActionPerformed(evt);
            }
        });

        comboCategory.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        comboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--" }));
        comboCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCategoryActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jlRequestTherapy.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jlRequestTherapy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlRequestTherapy.setText("Request Therapy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jlRequestTherapy, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(comboNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlTherapyCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(comboTherpay, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(220, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlRequestTherapy, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTherapyCenter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboTherpay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(431, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboTherpayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTherpayActionPerformed
        // TODO add your handling code here:
        comboCategory.removeAllItems();
        for(Network n: ecosystem.getNetworkList()){
            if(comboNetwork.getSelectedItem().toString().equalsIgnoreCase(n.getNetworkName())){
//                System.out.println("!!Network: "+n+": "+n.getEnterpriseDirectory().getEnterpriseList());
                for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                    if(e.getOrganizationName() != null && comboTherpay.getSelectedItem() != null && e.getOrganizationName().equalsIgnoreCase(comboTherpay.getSelectedItem().toString())){
                        for(Organization o: e.getOrganizationDirectory().getOrganizationList()){
                            comboCategory.addItem(o.getOrganizationName());
                        }
                    }
                }
            }
        }
        
    }//GEN-LAST:event_comboTherpayActionPerformed

    private void comboCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCategoryActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_comboCategoryActionPerformed

    private void comboNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNetworkActionPerformed
        // TODO add your handling code here:
//        System.out.println("Adding Emter: ");
        comboTherpay.removeAllItems();
        comboTherpay.addItem("--Select--");
//        System.out.println(cb_network.getSelectedItem().toString()+"");
        for(Network n: ecosystem.getNetworkList()){
            System.out.println("cb net@@@: "+comboNetwork.getSelectedItem());
            if(comboNetwork.getSelectedItem().toString().equalsIgnoreCase(n.getNetworkName())){
                System.out.println("Adding net@@@: "+comboNetwork.getSelectedItem());
                for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                System.out.println("Adding THer@@@: "+e.getOrganizationName());
                    if(e.getEnterpriseType().getValue().equalsIgnoreCase("therapy")){
                        
                        
                        comboTherpay.addItem(e.getOrganizationName());
                    }
                   
                }
            }
        }
    }//GEN-LAST:event_comboNetworkActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        boolean check;
        check=(!(comboTherpay.getSelectedItem()==null||comboNetwork.getSelectedItem()==null||comboCategory.getSelectedItem()==null));
        
        if(!check){
            JOptionPane.showMessageDialog(null, "Select proper options (or) doctors not available");
            return;
        }        
        PhysicianWorkRequest request = new PhysicianWorkRequest();
        request.setPatientAccount(Patient);
        Organization orga = null;
        request.setSender(accountUser);
        request.setStatus("Requested");

        for(Network n: ecosystem.getNetworkList()){
            if(n.getNetworkName().equalsIgnoreCase(comboNetwork.getSelectedItem().toString())){
                for(Enterprise e: n.getEnterpriseDirectory().getEnterpriseList()){
                    if(e instanceof Treatment&&e.getOrganizationName().equalsIgnoreCase(comboTherpay.getSelectedItem().toString())){
                        for(Organization o:e.getOrganizationDirectory().getOrganizationList()){
                            if(o.getOrganizationName().equalsIgnoreCase(comboCategory.getSelectedItem().toString())){
                                orga=o;
                                o.getWorkQueue().getWorkRequestList().add(request);
                                accountUser.getWorkQueue().getWorkRequestList().add(request);
                                JOptionPane.showMessageDialog(null, "Therapist service requested");
                            }
                        }
                    }
                }
            }
        }
        
        DoctorWorkAreaJPanel sa=new DoctorWorkAreaJPanel(processContainerUser,accountUser,org,Enterprise,ecosystem,Network);
        processContainerUser.add("Customer Adding",sa);
        CardLayout layout=(CardLayout)processContainerUser.getLayout();
        layout.next(processContainerUser);
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DoctorWorkAreaJPanel sa=new DoctorWorkAreaJPanel(processContainerUser,accountUser,org,Enterprise,ecosystem,Network);
        processContainerUser.add("Customer Adding",sa);
        CardLayout layout=(CardLayout)processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JComboBox<String> comboCategory;
    private javax.swing.JComboBox<String> comboNetwork;
    private javax.swing.JComboBox<String> comboTherpay;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jlCategory;
    private javax.swing.JLabel jlNetwork;
    private javax.swing.JLabel jlPatientId;
    private javax.swing.JLabel jlPatientName;
    private javax.swing.JLabel jlRequestTherapy;
    private javax.swing.JLabel jlTherapyCenter;
    private javax.swing.JTextField txtPatientID;
    private javax.swing.JTextField txtPatientName;
    // End of variables declaration//GEN-END:variables
}
