/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.DoctorRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Medical;
import Business.Person.Patient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DiagnosticsWorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author bhavana
 */
public class TestDataJPanel extends javax.swing.JPanel {
    JPanel processContainerUser;
    UserAccount accountUser;
    String id;
    Patient patient;
    String assist;
    Enterprise Enterprise;
    Medical organization;
    EcoSystem EcoSystem;
    Network Network;
    /**
     * Creates new form TestDataJPanel
     */
    public TestDataJPanel(JPanel userProcessContainer, UserAccount userAccount, String id,Patient patient,String assist,Enterprise enterprise,Medical organization, EcoSystem ecosystem,Network network) {
        initComponents();
        this.accountUser=userAccount;
        this.processContainerUser=userProcessContainer;
        this.id=id;
        this.patient=patient;
        this.assist=assist;
        this.Enterprise=enterprise;
        this.organization=organization;
        this.EcoSystem=ecosystem;
        this.Network=network;
        txtArea_chandu.setText(populatevalues());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOkay = new javax.swing.JButton();
        jlTestReport = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_chandu = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(0, 204, 204));

        btnOkay.setText("Okay");
        btnOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkayActionPerformed(evt);
            }
        });

        jlTestReport.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jlTestReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTestReport.setText("Test Report");

        txtArea_chandu.setEditable(false);
        txtArea_chandu.setBackground(new java.awt.Color(255, 255, 255));
        txtArea_chandu.setColumns(20);
        txtArea_chandu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtArea_chandu.setForeground(new java.awt.Color(255, 0, 51));
        txtArea_chandu.setRows(5);
        jScrollPane1.setViewportView(txtArea_chandu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(btnOkay, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                            .addComponent(jlTestReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlTestReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOkay)
                .addGap(191, 191, 191))
        );
    }// </editor-fold>//GEN-END:initComponents

    public String populatevalues(){
        String test="            ******************** TEST RESULTS ***********************\n";
        test+="\nPatient ID : "+id+"\n";
        test+="\nPatient Name : "+patient.getPatientName()+"\n";
        test+="\nLab Assistant :"+assist+"\n";
        test+="**************************************************";
        
        
        for(int i=0;i<accountUser.getWorkQueue().getWorkRequestList().size();i++){
            if(accountUser.getWorkQueue().getWorkRequestList().get(i) instanceof DiagnosticsWorkRequest){
                if((""+((DiagnosticsWorkRequest) accountUser.getWorkQueue().getWorkRequestList().get(i)).getPatient().getId()).equalsIgnoreCase(id)){
                    for(int j=0;j<((DiagnosticsWorkRequest) accountUser.getWorkQueue().getWorkRequestList().get(i)).getTests().size();j++){
                        test+="\n"+((DiagnosticsWorkRequest) accountUser.getWorkQueue().getWorkRequestList().get(i)).getTests().get(j) +" : "+((DiagnosticsWorkRequest) accountUser.getWorkQueue().getWorkRequestList().get(i)).getTestData().get(j)+"\n";
                    }
                }
            }
        
        }    
    return test;
    }
   
    
    private void btnOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkayActionPerformed
        // TODO add your handling code here:
        DoctorWorkAreaJPanel sa=new DoctorWorkAreaJPanel(processContainerUser,accountUser,organization,Enterprise,EcoSystem,Network);
        processContainerUser.add("Customer Adding",sa);
        CardLayout layout=(CardLayout)processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_btnOkayActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlTestReport;
    private javax.swing.JTextArea txtArea_chandu;
    // End of variables declaration//GEN-END:variables
}
