/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SystemAdminWorkArea;

import Business.EcoSystem;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author vidyavathipuli

 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    JPanel processContainerUser;
    EcoSystem ecoSystem;
    public SystemAdminWorkAreaJPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.processContainerUser=userProcessContainer;
        this.ecoSystem=ecosystem;

        populateTree();
    }
    
    public void populateTree(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnManageNetwork = new javax.swing.JButton();
        btn_Manage_Enterprise = new javax.swing.JButton();
        btn_Manage_Admin_Enterprise = new javax.swing.JButton();
        jlSystemAdministrator = new javax.swing.JLabel();
        jlWelcomeAdmin = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane.setDividerLocation(10);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 400));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1117, Short.MAX_VALUE)
        );

        jSplitPane.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setMaximumSize(new java.awt.Dimension(1200, 800));
        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 800));

        btnManageNetwork.setBackground(new java.awt.Color(204, 204, 204));
        btnManageNetwork.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });

        btn_Manage_Enterprise.setBackground(new java.awt.Color(204, 204, 204));
        btn_Manage_Enterprise.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btn_Manage_Enterprise.setText("Manage Enterprise");
        btn_Manage_Enterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Manage_EnterpriseActionPerformed(evt);
            }
        });

        btn_Manage_Admin_Enterprise.setBackground(new java.awt.Color(204, 204, 204));
        btn_Manage_Admin_Enterprise.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        btn_Manage_Admin_Enterprise.setText("Manage Enterprise Admin");
        btn_Manage_Admin_Enterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Manage_Admin_EnterpriseActionPerformed(evt);
            }
        });

        jlSystemAdministrator.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jlSystemAdministrator.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlSystemAdministrator.setText("SYSTEM ADMINISTRATION ");

        jlWelcomeAdmin.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        jlWelcomeAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlWelcomeAdmin.setText("Welcome Admin !");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(403, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnManageNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jlWelcomeAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btn_Manage_Enterprise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_Manage_Admin_Enterprise, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE))))
                .addGap(406, 406, 406))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlSystemAdministrator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jlSystemAdministrator)
                .addGap(18, 18, 18)
                .addComponent(jlWelcomeAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(btnManageNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_Manage_Enterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btn_Manage_Admin_Enterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(695, 695, 695))
        );

        jSplitPane.setRightComponent(jPanel2);

        add(jSplitPane, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        NetworkManagementJPanel manageNetworkJPanel=new NetworkManagementJPanel(processContainerUser, ecoSystem);
        processContainerUser.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btn_Manage_EnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Manage_EnterpriseActionPerformed
        EnterpriseManagementJPanel emj=new EnterpriseManagementJPanel(processContainerUser, ecoSystem);
        processContainerUser.add("manage enterprise",emj);
        CardLayout layout=(CardLayout)processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_btn_Manage_EnterpriseActionPerformed

    private void btn_Manage_Admin_EnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Manage_Admin_EnterpriseActionPerformed
        AdminsManagementJPanel amj=new AdminsManagementJPanel(processContainerUser, ecoSystem);
        processContainerUser.add("manage admins",amj);
        CardLayout layout=(CardLayout)processContainerUser.getLayout();
        layout.next(processContainerUser);
    }//GEN-LAST:event_btn_Manage_Admin_EnterpriseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JButton btn_Manage_Admin_Enterprise;
    private javax.swing.JButton btn_Manage_Enterprise;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JLabel jlSystemAdministrator;
    private javax.swing.JLabel jlWelcomeAdmin;
    // End of variables declaration//GEN-END:variables
}
